Repository nextcloud-libraries/nextcloud-password-confirmation, pull requests merged in 2022-09, with the labels that each got.

#378 Modernize package and add Vue dialog
  .github/workflows/l10n.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
  .gitignore
  .npmignore
  CHANGELOG.md
  README.md
  babel.config.js
  build/extract-l10n.mjs
  l10n/messages.pot
  lib/index.ts
  package-lock.json
  package.json
  src/components/Dialog.vue
  src/env.d.ts
  src/globals.ts
  src/main.ts
  src/utils/l10n.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement, 3. to review, accessibility

#384 Hide error message when reconfirming password and update message
  l10n/messages.pot
  src/components/Dialog.vue
Labels: bug, 3. to review

#383 v3.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#385 Fix and update README badges
  README.md
Labels: 3. to review

#387 Fix dialog not appearing when another modal is open
  CHANGELOG.md
  l10n/messages.pot
  package-lock.json
  package.json
  src/components/Dialog.vue
  src/globals.ts
  src/main.ts
Labels: bug, 3. to review, accessibility

#388 v3.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#393 Remove exports field to fix eslint and build errors
  CHANGELOG.md
  README.md
  package.json
Labels: bug, 3. to review

#394 v4.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#399 Don't check the password strength when the admin confirms their password
  src/components/Dialog.vue
Labels: bug, 3. to review

#400 Bump @nextcloud/vue to remove errors from console
  package-lock.json
  package.json
  tsconfig.json
Labels: bug, 4. to release

#401 Remove password policy checks completely to fix permanently disabled confirm button
  l10n/messages.pot
  package-lock.json
  package.json
  src/components/Dialog.vue
Labels: bug, 4. to release

#402 v4.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release
