Repository nextcloud-libraries/nextcloud-password-confirmation, pull requests merged in 2023-10, with the labels that each got.

#606 Fix `@nextcloud/l10n/gettext` import
  src/utils/l10n.ts
  tsconfig.json
Labels: bug

#607 Upgrade `@nextcloud/vue` lib to ^8.0.0-beta.7
  package-lock.json
  package.json
Labels: 3. to review

#609 feat: export isPasswordConfirmationRequired
  README.md
  src/main.ts
Labels: enhancement, 3. to review

#605 Improve password confirmation dialog
  l10n/messages.pot
  src/components/PasswordDialog.vue
Labels: 2. developing

#615 release: v4.1.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: 3. to review
