Repository nextcloud-libraries/nextcloud-password-confirmation, pull requests merged in 2023-11, with the labels that each got.

#634 Setup for Transifex
  .github/workflows/command-l10n-update.yml
  .github/workflows/transifex-approve-merge.yml
  transifex.yml
Labels: 3. to review

#666 Fix/do not mount to hidden modal
  src/main.ts
Labels: bug, 3. to review

#667 build: fix dev and watch build by specifying CSS chunk path
  package.json
  vite.config.mts
Labels: 3. to review

#669 v5.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 4. to release
