Repository nextcloud-libraries/nextcloud-password-confirmation, pull requests merged in 2024-01, with the labels that each got.

#678 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, 3. to review, automated

#692 fix: Adjust code indention to be consistent (tabs)
  src/components/PasswordDialog.vue
Labels: bug, 3. to review

#691 fix: Do not translate Exception error message
  l10n/messages.pot
  src/main.ts
Labels: bug, 3. to review

#696 Make package ESM by default
  build/extract-l10n.js
  package.json
  vite.config.ts
Labels: 3. to review

#693 fix: Adjust peer dependency on `@nextcloud/vue` to allow stable version
  package-lock.json
  package.json
Labels: bug, 3. to review

#694 chore: Update `@nextcloud/router` to 2.2.0 and update some dev-dependencies
  package-lock.json
  package.json
Labels: 3. to review

#695 chore: Update NPM to v10 to align with the version provided by LTS Node 20
  package-lock.json
  package.json
Labels: 3. to review

#698 enh: Compress translations to reduce bundle size
  src/env.d.ts
  src/utils/l10n.ts
  vite.config.ts
Labels: enhancement, 3. to review
